### ISSUE TITLE
Test client doesn't work!!!

### ISSUE THREAD

**Issue by forouhar-panah** [Dione-Software/dione#46]
Hi I'm looking into contributing to this project but before that i just wanted to run servers and test them.
but the dione-client-test doesn't work, here is what i did:

`dione-server --db-path node1 --ex 0.0.0.0:8010 --clear-address http://localhost:8010 --listen-address /ip4/0.0.0.0/tcp/0`

then it printed:
Clear Address => http://localhost:8010
Waiting for clear addr
Starting server
Web Service is listening on [0.0.0.0:8080]
thread 'actix-rt|system:0|arbiter:0' panicked at 'System is not running', /home/forouhar/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
Local node is listening on "/ip4/127.0.0.1/tcp/44927/p2p/12D3KooWGavF18Z2Y1aDj1vDykgqqJFoWW715pJJR4iu6dajxnWn"
Local node is listening on "/ip4/192.168.1.8/tcp/44927/p2p/12D3KooWGavF18Z2Y1aDj1vDykgqqJFoWW715pJJR4iu6dajxnWn"
Storer listening on 0.0.0.0:8010

then I added the env variable:
`export PEER="/ip4/127.0.0.1/tcp/44927/p2p/12D3KooWGavF18Z2Y1aDj1vDykgqqJFoWW715pJJR4iu6dajxnWn" `

after that i ran the second node:
`dione-server --db-path node2 --ex 0.0.0.0:8011 --clear-address http://localhost:8011 --listen-address /ip4/0.0.0.0/tcp/0 --web-http-port 8100`

it printed: 

Dialing
Local node is listening on "/ip4/127.0.0.1/tcp/40731/p2p/12D3KooWPyfKHszs6eDRGh5Q8V4MnfoUdXcVrvjWNYF6pKUb4SJx"
Local node is listening on "/ip4/192.168.1.8/tcp/40731/p2p/12D3KooWPyfKHszs6eDRGh5Q8V4MnfoUdXcVrvjWNYF6pKUb4SJx"
Adding peer 12D3KooWGavF18Z2Y1aDj1vDykgqqJFoWW715pJJR4iu6dajxnWn with address /ip4/127.0.0.1/tcp/44927/p2p/12D3KooWGavF18Z2Y1aDj1vDykgqqJFoWW715pJJR4iu6dajxnWn/p2p/12D3KooWGavF18Z2Y1aDj1vDykgqqJFoWW715pJJR4iu6dajxnWn
Clear Address => http://localhost:8011
Waiting for clear addr
Starting server
Web Service is listening on [0.0.0.0:8100]
thread 'actix-rt|system:0|arbiter:0' panicked at 'System is not running', /home/forouhar/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Storer listening on 0.0.0.0:8011

after this i tried to run client:
`dione-test-client client1 --server http://localhost:8010`

but it does't work it printed this:

Error: Server threw error with responding status => Status { code: Unknown, message: "transport error", source: None }

and on the server it printed this:

Adding peer 12D3KooWPyfKHszs6eDRGh5Q8V4MnfoUdXcVrvjWNYF6pKUb4SJx with address /ip4/127.0.0.1/tcp/33098
Closest Peers => []
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', dione-server/src/network/mod.rs:329:48
thread 'tokio-runtime-worker' panicked at 'Sender not to be dropped: RecvError(())', thread 'dione-server/src/network/mod.rstokio-runtime-worker:' panicked at '134Sender not to be dropped: RecvError(()):', 24dione-server/src/network/mod.rs
:124:24
thread 'tokio-runtime-worker' panicked at 'Command receiver not to be dropped.: SendError(GetClosestPeer { addr: [], sender: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) } })', dione-server/src/network/mod.rs:133:14

I tried many times but it didn't work, maybe i did something wrong.

**Comment by umgefahren** [comment]
First of all thanks for considering to contribute. The whole thing is currently extremely unstable and I'm currently troubleshooting your error. I swear it once worked, so please be patience. I'm extremely graceful for your willingness to contribute.

**Comment by umgefahren** [comment]
I think I found the issue and it's incredibly dumb. But please check if it works on your side too, because there is some uncertainty in the systems behaviour.

To solve the issue the first connection from a client hast to go the second server started. I.e. you first have to connect to `http://127.0.0.1:8011`.

**Comment by forouhar-panah** [comment]
Thanks, the first client connects to the second server successfully but the second client doesn't connect to the first server.

`dione-test-client client2 --server http://127.0.0.1:8010`

it printed: Error: Server threw error with responding status => Status { code: Unknown, message: "transport error", source: None }

and this is logs on the first server:

Clear Address => http://localhost:8010
Waiting for clear addr
Starting server
Web Service is listening on [0.0.0.0:8080]
thread 'actix-rt|system:0|arbiter:0' panicked at 'System is not running', /home/forouhar/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-rt-1.1.1/src/system.rs:78:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Local node is listening on "/ip4/127.0.0.1/tcp/44665/p2p/12D3KooWFLtSF1hjfLVvvDrhoY9ja9vBUtBi3rGJ4fjpLiQyhywP"
Local node is listening on "/ip4/192.168.1.8/tcp/44665/p2p/12D3KooWFLtSF1hjfLVvvDrhoY9ja9vBUtBi3rGJ4fjpLiQyhywP"
Storer listening on 0.0.0.0:8010
Adding peer 12D3KooWBdio6mo2kGa3DJ8pVr11FQucQzfMy29LRwputWVQycQx with address /ip4/127.0.0.1/tcp/45230
Adding peer 12D3KooWBdio6mo2kGa3DJ8pVr11FQucQzfMy29LRwputWVQycQx with address /ip4/127.0.0.1/tcp/45234
Oct 05 18:17:00.452  INFO save_message: dione_server::tonic_responder::message_storer: Processing Request
Propagating [25, 136, 153, 216, 178, 98, 73, 50, 149, 242, 116, 79, 89, 124, 135, 162]
Closest Peers => []
thread 'tokio-runtime-worker' panicked at 'called `Option::unwrap()` on a `None` value', dione-server/src/network/mod.rs:329:48
thread 'tokio-runtime-worker' panicked at 'Sender not to be dropped: RecvError(())', dione-server/src/network/mod.rsthread ':tokio-runtime-worker134' panicked at ':Sender not to be dropped: RecvError(())24', 
dione-server/src/network/mod.rs:124:24
thread 'tokio-runtime-worker' panicked at 'Command receiver not to be dropped.: SendError(GetClosestPeer { addr: [], sender: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) } })', dione-server/src/network/mod.rs:133:14
thread 'tokio-runtime-worker' panicked at 'Command receiver not to be dropped.: SendError(GetClosestPeer { addr: [], sender: Sender { inner: Some(Inner { state: State { is_complete: false, is_closed: false, is_rx_task_set: false, is_tx_task_set: false } }) } })', dione-server/src/network/mod.rs:133:14


for once both clients connected successfully, so I don't know may be there is a problem with my system.
anyway thanks for respond, I'll keep trying.
